### PR TITLE
Touch-Up  👍

### LINKED ISSUE #7: Links break somtimes
if you deploy this with out naming it [username].gitHub.io it breaks a bunch of stuff

### PR DESCRIPTION
**Pull request by om3ga6400**
<h1>Touch-Up</h1>
<h2>Readme</h2>
<h3>Additions</h3>
-format all the tags
<h3>Removals</h3>
-removed the extra line at the bottom
<h2>404 Page</h2>
<h3>Additions</h3>
-replaced all the hard-coded links
<h3>Removals</h3>
-none
<h2>Other</h2>
<h3>Additions</h3>
-changed the settings tab link to /settings instead of /#
-created a template settings page in /pages
<h3>Removals</h3>
-none
<h2>Sum-Up</h2>
This fixes #7 and #8 and makes it so that when deployed under a different link the other pages are not messed up, also instead of having a non-existent page for the settings it just says that it's "Under Construction".

### CODE REVIEW

**Comment by ImPosh** [comment]
bro  is not active

**Comment by om3ga6400** [comment]
> bro is not active

wdym

**Comment by ImPosh** [comment]
bro has not updated his site in like 3 years

**Comment by om3ga6400** [comment]
> bro has not updated his site in like 3 years

its only been like 7 months

**Comment by om3ga6400** [comment]
closing because I made a more easily read pull and also removed some accidental commits and merged a few comments into each other

**Pull request closed without merging**
